### ISSUE TITLE
Build failed to parse `build-depends` from .cabal

### ISSUE THREAD

**Issue by KtorZ** [phadej/file-embed-lzma#1]
Hey! Great work pulling out this new release on `servant-swagger-ui` :)
Trying to make use of `servant-swagger-ui-redoc`, I got some weird issues with cabal (via stack) when trying to configure this library. Cabal complains about a parsing error line 54 / invalid build-depends:

- https://github.com/phadej/file-embed-lzma/blob/master/file-embed-lzma.cabal#L54

I've actually never seen this syntax before, is it something specific to cabal >2.x.x ? Do you think there's a chance to make this compatible with cabal 1.24 ?

**Comment by phadej** [comment]
the ^>= 2.0 syntax is available since Cabal-2.0. The latest cabal-install and stack (at least `stack-1.6.5) should be ok with them.

I'd rather not go back to `>= x.y.z && <x.(y+1)`, if there aren't really really good reason.

**Comment by KtorZ** [comment]
That's what I thought indeed about the syntax. I'll look into upgrading to a more recent LTS then and backport the change on swagger-ui for now :)
Thanks for the inputs :+1:

**Comment by phadej** [comment]
@KtorZ note that you don't need to update to newer LTS (you just need to add new dependencies to `extra-deps`), you need to update the `stack` executable. Try `stack upgrade`.
